name: Package
on:
  push:
    branches:
      - main
    paths:
      - 'CleanArchitecture.nuspec'
jobs:
  publish:
    name: Publish to NuGet.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Remove UserSecret tags from project files
        run: |
          find . -name '*.csproj' -type f -exec sed -i 's/<UserSecretsId>.*<\/UserSecretsId>//g' {} \;

      - uses: nuget/setup-nuget@v2
        with:
          nuget-version: '6.x'

      - name: Create the package
        run: nuget pack CleanArchitecture.nuspec -NoDefaultExcludes
        
      - name: Publish the package
        run: nuget push *.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}} 
